<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<h2>Add Role</h2>

<?php echo $this->tag->form("/index/addroledata"); ?>

<p>
  <label for="title">Role</label>
  <?php echo $this->tag->select(
[
  'newrole',
    [
      'default' => 'Choose Option',
      'admin' => 'Admin', 
      'customer' => 'Customer',
      'guest' => 'Guest',

    ],
  
]
); ?>
</p>
<p>
        <?php echo $this->tag->submitButton("Add Role"); ?><br>
    </p>
</form>
</body>
</html>