<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<h2>Add Role</h2>

<?php echo $this->tag->form("/index/addusers?role=".$this->request->getQuery('role')); ?>
<p>
<label for="name">Name</label>
    <?php echo $this->tag->textField("name"); ?>
</p>
<p>
<label for="email">Email</label>
    <?php echo $this->tag->textField("email"); ?>
</p>
<p>
<label for="password">Password</label>
    <?php echo $this->tag->textField("password"); ?>
</p>

<p>
  <label for="title">Role</label>
  <?php echo $this->tag->select(
[
  'newrole',
    [
      'default' => 'Choose Option',
      'admin' => 'Admin', 
      'customer' => 'Customer',
      'guest' => 'Guest',

    ],
  
]
); ?>
</p>
<p>
        <?php echo $this->tag->submitButton("Add Role"); ?><br>
    </p>
</form>
</body>
</html>