<form method="POST" action="">

<label for="locale">Choose a language:</label>

<select name="locale" id="locale" onchange="submit()">
  <option value="none">None</option>
  <option value="en_US">US</option>
  <option value="en">English</option>
  <option value="nl_NL">Dutch</option>
</select>
</form>
<?php
// echo $this->Locale->_('Add Product');
   


?>
<?php
echo $this->tag->linkTo(
    [
        '/index/addproduct',
        $this->Locale->_('Add Product'),
        'class' => 'btn btn-primary w-25'
    ]
).'<br> <br>';
echo $this->tag->linkTo(
    [
        '/index/listproduct',
        $this->Locale->_('List Products'),
        'class' => 'btn btn-primary w-25'
    ]
).'<br>'.'<br>';
echo $this->tag->linkTo(
    [
        '/index/orderplace',
        $this->Locale->_('Place Order'),
        'class' => 'btn btn-primary w-25'
    ]
).'<br> <br>';
echo $this->tag->linkTo(
    [
        '/index/listorder',
        $this->Locale->_('Show Orders'),
        'class' => 'btn btn-primary w-25'
    ]
).'<br> <br>';
echo $this->tag->linkTo(
    [
        '/index/settings',
        $this->Locale->_('Settings'),
        'class' => 'btn btn-primary w-25'
    ]
).'<br> <br>';
echo $this->tag->linkTo(
    [
        '/index/addrole',
        $this->Locale->_('Add Role'),
        'class' => 'btn btn-primary w-25'
    ]
).'<br> <br>';
echo $this->tag->linkTo(
    [
        '/index/addcomponent',
        $this->Locale->_('Add Component'),
        'class' => 'btn btn-primary w-25'
    ]
).'<br> <br>';
echo $this->tag->linkTo(
    [
        '/index/adduser',
        $this->Locale->_('Add User'),
        'class' => 'btn btn-primary w-25'
    ]
);
