<?php
$this->cache->set('Setting', $this->Locale->_('Settings'));
$this->cache->set('AddProduct', $this->Locale->_('Add Product'));
$this->cache->set('ListProduct', $this->Locale->_('List Product'));
$this->cache->set('PlaceOrder', $this->Locale->_('Place Order'));
$this->cache->set('ShowOrders', $this->Locale->_('Show Orders'));
$this->cache->set('AddRole', $this->Locale->_('Add Role'));
$this->cache->set('AddComponent', $this->Locale->_('Add Component'));
$this->cache->set('AddUser', $this->Locale->_('Add User'));
$this->cache->set('TryValidTokenPlease', $this->Locale->_('Try Valid Token Please'));
$this->cache->set('Tokennotfound', $this->Locale->_('Token not found'));
// $this->cache->set('settings', $this->Locale->_('Settings'));






?>
<form method="POST" action="">

<label for="locale">Choose a language:</label>

<select name="locale" id="locale" onchange="submit()">
  <option value="none">None</option>
  <option value="en_US">US</option>
  <option value="en">English</option>
  <option value="nl_NL">Dutch</option>
</select>
</form>
<?php
// echo $this->Locale->_('Add Product');
   


?>
<?php
echo $this->tag->linkTo(
    [
        '/index/addproduct',
        $this->cache->get('AddProduct'),
        'class' => 'btn btn-primary w-25'
    ]
).'<br> <br>';
echo $this->tag->linkTo(
    [
        '/index/listproduct',
        $this->cache->get('ListProduct'),
        
        'class' => 'btn btn-primary w-25'
    ]
).'<br>'.'<br>';
echo $this->tag->linkTo(
    [
        '/index/orderplace',
        $this->cache->get('PlaceOrder'),
        'class' => 'btn btn-primary w-25'
    ]
).'<br> <br>';
echo $this->tag->linkTo(
    [
        '/index/listorder',
        $this->cache->get('ShowOrders'),
        'class' => 'btn btn-primary w-25'
    ]
).'<br> <br>';
echo $this->tag->linkTo(
    [
        '/index/settings',
        $this->cache->get('Setting'),
        'class' => 'btn btn-primary w-25'
    ]
).'<br> <br>';
echo $this->tag->linkTo(
    [
        '/index/addrole',
        $this->cache->get('AddRole'),
        'class' => 'btn btn-primary w-25'
    ]
).'<br> <br>';
echo $this->tag->linkTo(
    [
        '/index/addcomponent',
        $this->cache->get('AddComponent'),
        'class' => 'btn btn-primary w-25'
    ]
).'<br> <br>';
echo $this->tag->linkTo(
    [
        '/index/adduser',
        $this->cache->get('AddUser'),
        'class' => 'btn btn-primary w-25'
    ]
);
