<?php
echo $this->tag->linkTo(
    [
        '/index/addproduct',
        'Add Products',
        'class' => 'btn btn-primary w-25'
    ]
).'<br> <br>';
echo $this->tag->linkTo(
    [
        '/index/listproduct',
        'List Products',
        'class' => 'btn btn-primary w-25'
    ]
).'<br>'.'<br>';
echo $this->tag->linkTo(
    [
        '/index/orderplace',
        'Place Order',
        'class' => 'btn btn-primary w-25'
    ]
).'<br> <br>';
echo $this->tag->linkTo(
    [
        '/index/listorder',
        'Show Orders',
        'class' => 'btn btn-primary w-25'
    ]
).'<br> <br>';
echo $this->tag->linkTo(
    [
        '/index/settings',
        'Settings',
        'class' => 'btn btn-primary w-25'
    ]
).'<br> <br>';
echo $this->tag->linkTo(
    [
        '/index/addrole',
        'Add Role',
        'class' => 'btn btn-primary w-25'
    ]
).'<br> <br>';
echo $this->tag->linkTo(
    [
        '/index/addcomponent',
        'Add Component',
        'class' => 'btn btn-primary w-25'
    ]
).'<br> <br>';
echo $this->tag->linkTo(
    [
        '/index/adduser',
        'Add User',
        'class' => 'btn btn-primary w-25'
    ]
);
